DROP TABLE IF EXISTS GOOD;

CREATE TABLE GOOD (
       ID INT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(60) NOT NULL
     , COST INTEGER NOT NULL
     , STORAGE_QUANTITY INTEGER
     , DESCRIPTION VARCHAR(2000)
     , PHOTO BLOB
     , PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS DELIVERY;

CREATE TABLE DELIVERY (
       ID INT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(60) NOT NULL
     , ID_GOOD INTEGER NOT NULL
     , ID_ORDER INTEGER NOT NULL
     , QUANTITY INTEGER
     , UNIQUE UQ_DELIVERY_1 (ID_GOOD, ID_ORDER)
     , PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ORDER;

CREATE TABLE ORDER (
       ID INT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(60) NOT NULL
     , DESCRIPTION VARCHAR(2000)
     , PRIMARY KEY (ID)
);

